package texts

var (
	CatalogBtn       = "📦 Каталог"
	ProfileBtn       = "👤 Профиль"
	HelpBtn          = "☎️ Помощь"
	PurchasesBtn     = "📜 Мои покупки"
	RefillBalanceBtn = "💰 Пополнить баланс"
	StartMenuBtn     = "↩️ На главную"
	AdminPanelBtn    = "♿️ Админ панель"

	PurchaseInlineBtn = "%.2f₽ | %d x %s"
	BuyBtn            = "🛒 Купить"
	BackBtn           = "⬅️ Назад"
	MainMenuInlineBtn = "↩️ В главное меню"
	CatalogRootBtn    = "↩️ В корень каталога"
	CancelBtn         = "❌ Отмена"
	ConfirmBtn        = "✅ Подтвердить"
	PrevPageBtn       = "⬅️"
	NextPageBtn       = "➡️"
	ProfileRefreshBtn = "🔄 Обновить"

	StartMsg          = "🤙 Привет, *%s*!"
	ProfileMsg        = "👤 *@%s*\nℹ️ `%d`\n\n💰 Баланс: *%.2f* ₽\n📝 Покупок: *%d*\n💵 Потрачено: *%.2f* ₽"
	HelpMsg           = "☎️ Саппорт *%s*"
	PurchasesMsg      = "🛒 Последние покупки:"
	ProductMsg        = "📦 *%s*\n💰 %.2f ₽\n%s Доступно: *%d*\n\n%s\n\n💰 Доступный баланс: %.2f ₽"
	CatalogMsg        = "*📦 Каталог товаров*"
	CategoryMsg       = "📦 Категория: *%s*\n%s\n\n💰 Доступный баланс: %.2f ₽"
	CatalogEmptyMsg   = "_📦 Пока здесь пусто_"
	ProductBoughtMsg  = "✅ Покупка совершена! Куплено: *%d* шт.\n\nℹ️ %s\n\n*📦 Товар(ы):*\n%s"
	PurchaseDetailMsg = "📦 *%s*\n💰 %.2f ₽ (%d шт.)\n🗓%s\nℹ️ %s\n\n*🛒 Товар(ы):*\n%s"
	PurchasesEmptyMsg = "📜 У вас пока нет покупок"
	RefillMsg         = "💰 Пополнение баланса в разработке"

	AdminMsg         = "🔐 Панель администратора:\n\n🔑 Код для входа: `%s`\n⏳ Действителен 30 секунд"
	AdminMsgWithLink = "🔐 Панель администратора:\n\n🔑 Код для входа: `%s`\n⏳ Действителен 30 секунд\n\n🔗 Ссылка: %s"
	AdminCodeErrMsg  = "❌ Не удалось выпустить код для входа, попробуйте ещё раз."
	NotAdminMsg      = "⛔️ Команда доступна только администраторам."

	PleaseStartMsg = "👋 Сначала нажмите /start"
	BannedMsg      = "🚫 Вы заблокированы."

	AskQuantityMsg            = "🔢 Сколько штук «%s» купить?\n\n_Введите число или выберите на клавиатуре_"
	InsufficientStockMsg      = "❌ В наличии только *%d* шт. Введите другое количество."
	ConfirmPurchaseMsg        = "🧾 Подтвердите покупку:\n\n📦 *%s*\n🔢 Количество: *%d*\n💰 Сумма: *%.2f ₽*"
	InvalidQuantityMsg        = "⚠️ Введите целое число от 1 до 20."
	AskRefillAmountMsg        = "💰 Введите сумму пополнения в ₽:"
	InvalidAmountMsg          = "⚠️ Введите положительное число."
	RefillInvoiceMsg          = "💳 Оплатите *%.2f ₽* по кнопке ниже."
	PayBtn                    = "💳 Оплатить"
	ErrInsufficientBalanceMsg = "❌ Не хватает баланса на покупку."
	ErrOutOfStockMsg          = "❌ Товар закончился."
	ErrProductInactiveMsg     = "❌ Товар больше не продаётся."
	ErrTooManyProductsMsg     = "❌ Слишком большое количество за раз (максимум 20)."
	ErrGenericMsg             = "❌ Что-то пошло не так, попробуйте позже."
)
